### DISCUSSION TITLE
how to make no prompt 'Password for elastic' every time when starting the job using fscrawler

### DISCUSSION THREAD

**Discussion by lxia-hub** [dadoonet/fscrawler#1120] [Q&A] [answered]
I've set fscrawler as a service. And there is a password issue for elastic.

first, have configured username and password in the file `_settigns.yaml`.  

```yml
name: "test"
elasticsearch:
  username: "elastic"
  password: "changeme"
```

and the command of starting the job:

```sh 
fscrawler --username elastic --config_dir ./QM qualcomm01
```

the issue is when I execute the command launch the tool fscrawler, it needs to input the password of elastic. 

![image](https://user-images.githubusercontent.com/69227782/112941636-8722eb80-9161-11eb-9a2a-9b7e80e668f9.png)

 If there is a way to not input the password any more.
