### DISCUSSION TITLE
does not index content

### DISCUSSION THREAD

**Discussion by sarce666** [dadoonet/fscrawler#1303] [General]
hello 

i trying to index data to elasticloud and worksoace
here is the conf : 

```
name: "feeds"
fs:
  url: "/feeds"
  update_rate: "15m"
  json_support: false
  filename_as_id: false
  add_filesize: true
  remove_deleted: true
  add_as_inner_object: false
  store_source: false
  index_content: true
  attributes_support: false
  raw_metadata: true
  xml_support: false
  index_folders: true
  lang_detect: false
  continue_on_error: true
  ocr:
    language: "eng"
    enabled: true
    pdf_strategy: "ocr_and_text"
  follow_symlinks: false
elasticsearch:
  username: ""
  password: ""
  nodes:
  - cloud_id: 
workplace_search:
  access_token: ""
  key: ""
  server: ""
  bulk_size: 1000
  flush_interval: "5s"
  byte_size: "10mb"
```

it works fine but in elasticsearch i dont have the content ( which i have into workspace ) 

when launch fscrwaler it found the pdf to index 
`15:39:35,340 DEBUG [f.p.e.c.f.FsParserAbstract] [/florent/2021-09-28--Invoice_202110.pdf] can be indexed: [true]
15:39:35,340 DEBUG [f.p.e.c.f.FsParserAbstract]   - file: /florent/2021-09-28--Invoice_202110.pdf`

but it index it with those fields : Available fields
9
_id
_index
score
_type
file.​content_type
file.​filename
path.​real
path.​root
path.​virtual

and i have not content
![Screenshot 2021-11-09 at 16 48 27](https://user-images.githubusercontent.com/84068406/140957214-9cd5e669-ff97-4115-8af7-df875570211e.png)
t 

**but in workplace it is indexed with content**

thanks for your help and bravo for fscrawler

**Comment by dadoonet** [comment]
Hey 👋🏼 


Could you edit your post and format code/settings/logs with `<>` icon or markdown?

**Reply by sarce666** [reply]
sorry 

i just did it thanks

**Comment by dadoonet** [comment]
Hey 👋🏼 


Could you edit your post and format code/settings/logs with `<>` icon or markdown?

**Comment by sarce666** [comment]
i might have found the issue 
in my conf file i try to index it with elastic cloud and workspace
it looks like if it put both it only index it in workspace, if i remove workspace it index perfectly the elastic 
then should i create 2 different files ?

**Reply by dadoonet** [reply]
No. One single file.

If you want to index in workplace search, you need to set the elasticsearch part and the workplace search part.

I'll post in a moment what I'm exactly using right now for this. Stay tuned.

**Comment by dadoonet** [comment]
Here is the typical settings you could use for Workplace Search on elastic cloud:

```yml
---
name: "test"
fs:
  url: "/path/to/dir"
elasticsearch:
  username: "elastic"
  password: "PASSWORD"
  nodes:
  - cloud_id: "CLOUD_ID"
workplace_search:
  server: "WORKPLACE_SEARCH_URL"
```

**Reply by dadoonet** [reply]
So try something like:

```yml
name: "feeds"
fs:
  url: "/feeds"
elasticsearch:
  username: "elastic"
  password: "PASSWORD"
  nodes:
  - cloud_id:  "CLOUD_ID"
workplace_search:
  server: "WORKPLACE_SEARCH_URL"
```
