### DISCUSSION TITLE
File path is only filename after ingestion using the REST Gateway

### DISCUSSION THREAD

**Discussion by Bradfordio** [dadoonet/fscrawler#1418] [Q&A]
Hello,

I'm relatively new to fscrawler so apologies if this is a very basic mistake I'm making on my end.

We are currently attempting to ingest millions of files of all different filetypes stored on an S3 bucket into ES. To accomplish this we fscrawler running as an REST gateway on a RH Ec2 instance. We also have a python script which does the following:

- Reads from an SQS queue where the messages are an object key.
![image](https://user-images.githubusercontent.com/67659644/164699178-1cb2f226-968a-4ec6-996b-e84fd4d571c5.png)

- Reads the object key and if there are any prefixes (folders in S3) it then makes the same directory structure on the ec2 instance:
![image](https://user-images.githubusercontent.com/67659644/164699253-74be3e8f-def2-40b4-b4ce-7ef96c7c651d.png)

- Downloads the file with the correct filename to that location
![image](https://user-images.githubusercontent.com/67659644/164699441-9830c360-0d7f-49ab-98d3-fb3bfe2b0f14.png)

- Uploads the file to ES index via curl command

```
cmd = os.system("curl -F file=@'" + directory + "/" + filename + "' -F id=\"" + uid + "\" http://127.0.0.1:8080/fscrawler/_upload")
```

This process does work for us and we have successfully ingested many files. However one thing we have noticed which is vital for us is that the path fields for both virtual and real are only returning with just the filename:

```json
"path" : {
            "virtual" : "sample-data-audio-wav.wav",
            "real" : "sample-data-audio-wav.wav"
          }
```

Can anyone please help me to understand why the linux file path is missing?

Config:
fscrawler mappings are the default: 

https://github.com/dadoonet/fscrawler/blob/master/settings/src/main/resources/fr/pilato/elasticsearch/crawler/fs/_default/7/_settings.json

fscrawler settings:

```yml
---
name: "path_test"
fs:
  url: "/tmp/es"
  update_rate: "15m"
  excludes:
  - "*/~*"
  json_support: false
  filename_as_id: true
  add_filesize: true
  remove_deleted: true
  add_as_inner_object: false
  store_source: true
  index_content: true
  attributes_support: true
  raw_metadata: true
  xml_support: false
  index_folders: false
  lang_detect: false
  continue_on_error: false
  ocr:
    language: "eng"
    enabled: true
    pdf_strategy: "ocr_and_text"
  follow_symlinks: true
elasticsearch:
  nodes:
  - url: "***"
  bulk_size: 100
  flush_interval: "5s"
  index: "path_test"
rest:
  url: "http://127.0.0.1:8080/fscrawler"
```
