### DISCUSSION TITLE
Got following messge "Unable to extract PDF content -> Unable to end a page -> TesseractOCRParser timeout"

### DISCUSSION THREAD

**Discussion by ScottCov** [dadoonet/fscrawler#1622] [General]
I realize this maybe better suited to a Tika/Tesseract forum but I got this message while running fscrawler....

> 10:11:16,387 WARN  [f.p.e.c.f.t.TikaDocParser] Failed to extract [100000] characters of text for [/tmp/es/21-11369/338.pdf]: Unable to extract PDF content -> Unable to end a page -> TesseractOCRParser timeout

Anyone have any ideas? PDF is attached.
[338.pdf](https://github.com/dadoonet/fscrawler/files/10933308/338.pdf)

**Comment by dadoonet** [comment]
I tested your file and it worked well.

![image](https://user-images.githubusercontent.com/274222/227190360-9c2fbce9-5d2a-4127-8419-08d05c681fa1.png)

But it took a huge amount of time to parse it. Almost 4 minutes. 
I believed that you got something like a timeout in that case?

I ran:

```yaml
---
name: "test"
fs:
  url: "/tmp/es"
elasticsearch:
  nodes:
  - url: "https://INSTANCE.es.europe-west1.gcp.cloud.es.io"
  username: "elastic"
  password: "PASSWORD"
```

and:

```sh
docker pull dadoonet/fscrawler
docker run -it --rm -v "`pwd`"/config:/root/.fscrawler -v "`pwd`"/files:/tmp/es:ro dadoonet/fscrawler fscrawler test --debug --restart
```
