### DISCUSSION TITLE
Cant index metadata from mp3 files

### DISCUSSION THREAD

**Discussion by zxcvbnm3057** [dadoonet/fscrawler#2064] [Q&A]
Hi All,

Im trying to use fscrawler to index metadata like singer, album and lyrics so that I can seach for a local music in elasticsearch. And here is my job.yml

```
---
name: "music"

fs:
  url: "/tmp/es"
  update_rate: "15m" 
  includes: ["*.mp3"]
  excludes: ["*/~*"] 
  json_support: false
  filename_as_id: false
  add_filesize: true
  index_content: false

elasticsearch:
  nodes:
    - url: "http://elasticsearch:9200"
  username: "elastic"
  password: "xxxxxxxxxxx"
  ssl_verification: false
  index: "test"

metadata:
  audio:
    include: true 
    exiftool:
      path: "/usr/bin/exiftool"
    mp3:
      id3v1: true
      id3v2: true
      lyrics: true
      cover: true

settings:
  bulk_size: 50 
  ocr: false
```

Im using a custom docker image base on dadoonet/fscrawler:2.10-SNAPSHOT and here is my docker file

```
FROM dadoonet/fscrawler:2.10-SNAPSHOT

RUN apt-get update && apt-get install -y \
    libimage-exiftool-perl \  
    ffmpeg \            
    && rm -rf /var/lib/apt/lists/* 
```

And I can be sure that my test.mp3 can be parsed with command `exiftool -j -g1 /tmp/es/test.mp3`.

And I have also grant full access for the user in docker, whose user id is 1001 and group id is 1001
```
-rwxr-xr-x 1 1001 1001 3785241 Apr 12 07:11 test.mp3
```

I have searched about this everywhere and also trying to ask help from chatgpt, but still nothing helpful. What did I missed?

**Comment by dadoonet** [comment]
What is this configuration? Where did you see it?


```yaml
metadata:
 audio:
   include: true
   exiftool:
     path: "/usr/bin/exiftool"
   mp3:
     id3v1: true
     id3v2: true
     lyrics: true
     cover: true

```
