### DISCUSSION TITLE
ocr_text option for pdf files gets poor text results

### DISCUSSION THREAD

**Discussion by mark-faster-outcomes** [dadoonet/fscrawler#2068] [General]
I'm  2.10-SNAPSHOT. I have large pdf files ( >25m) that I need to index. The only `pdf_strategy` that seems to work properly is `"ocr_only"`. The other options often missing words in the text and/or fail to preserve spacing ( I am `preserve_interword_spacing = true` ) and `page_seg_mode = 6`. I used `pdftotext` from the popper_utils and it extracts the text properly on my sample document. The problem with using `ocr_only` is that it can be very slow (>20 mins) on a large pdf file. Often the pdfs only contain text but I don't want to run the risk and missing some images that might contain text. 

Here are my `_settings.yml`

```yaml
ocr:
    # optional: enable or disable OCR
    enabled: true

    # optional: language to use for OCR
    language: "eng"
    # optional: path to the Tesseract binary
    #path: "/path/to/tesseract/if/not/available/in/PATH"
    # optional: path to the Tesseract tessdata directory
    #data_path: "/path/to/tesseract/tessdata/if/needed"
    # optional: the OCR output type, either txt or hocr
    output_type: txt
    # optional: the OCR strategy, either auto, no_ocr, ocr_only, ocr_and_text
    pdf_strategy: no_ocr
    # optional: the mode to use for page orientation from 0 to 13
    page_seg_mode: 6 # automatic mode
    # optional: if true, we will try to preserve interword spacing
    preserve_interword_spacing: true
```

BTW, I might consider just using pdftotext to get the text out of the pds, but it's not clear to me how I could override the pdf file handler in fscrawler to use something that I cook up.

Thanks!
