### ISSUE TITLE
Raw metadata not being populated for PDF documents

### ISSUE THREAD

**Issue by blevine** [dadoonet/fscrawler#1024]
**Describe the bug**

I'm running a test on 3 PDF documents. The properties under "file", "path", "attributes" appear to be extracted and stored in Elasticsearch correctly.  However raw metadata is not.  The metadata property is an empty object {}.

**Job Settings**

```yml
---
name: "test_job"
fs:
  url: "/Users/blevine/work/es/fulfillment/test_docs"
  update_rate: "15m"
  excludes:
  - "*/~*"
  json_support: false
  filename_as_id: true
  add_filesize: true
  remove_deleted: true
  add_as_inner_object: false
  store_source: false
  index_content: false
  attributes_support: true
  raw_metadata: true
  xml_support: false
  index_folders: false
  lang_detect: false
  continue_on_error: false
  ocr:
    language: "eng"
    enabled: true
    pdf_strategy: "ocr_and_text"
  follow_symlinks: false
elasticsearch:
  nodes:
  - url: "http://127.0.0.1:9200"
  bulk_size: 100
  flush_interval: "5s"
  byte_size: "10mb"
```

**Expected behavior**

Raw metadata should be populated.

Note:  exiftool returns the following
```
[{
  "SourceFile": "BOOK_COS_Release_Notes.pdf",
  "ExifToolVersion": 12.08,
  "FileName": "BOOK_COS_Release_Notes.pdf",
  "Directory": ".",
  "FileSize": "5.6 MB",
  "FileModifyDate": "2020:10:27 12:18:40-04:00",
  "FileAccessDate": "2020:10:27 12:19:04-04:00",
  "FileInodeChangeDate": "2020:10:27 12:18:40-04:00",
  "FilePermissions": "rw-r--r--",
  "FileType": "PDF",
  "FileTypeExtension": "pdf",
  "MIMEType": "application/pdf",
  "PDFVersion": 1.5,
  "Linearized": "No",
  "Encryption": "Standard V1.3 (40-bit)",
  "UserAccess": "Extract",
  "Title": "Release Notes",
  "Creator": "DocBook XSL Stylesheets V1.79.1",
  "Author": "Ab Initio",
  "Producer": "XEP 4.30.961",
  "Product": "Co>Operating System",
  "Lang": "en-US",
  "Internal": false,
  "ProdVer": "4.0.2",
  "Trapped": false,
  "CreateDate": "2020:10:14 19:26:12Z",
  "ModifyDate": "2020:10:14 19:26:12Z",
  "PageCount": 286,
  "PageMode": "UseOutlines",
  "Warning": "XMP format error (no closing tag for ?)",
  "TaggedPDF": "Yes",
  "Language": "en"
}]
```

**Versions:**
 - OS: MacOS
 - Version 2.7-SNAPSHOT
