### ISSUE TITLE
[Question] Best practise when indexing tens of thousands of files

### ISSUE THREAD

**Issue by TommyLike** [dadoonet/fscrawler#1032]
**Describe the bug**

This is not a bug, we use fscrawler for our repo folder that has tens of thousands of rpm files inside for the purpose of file searching via ES, this is how we configure it:
```
  _settings.yaml: |
    name: "openeuler"
    fs:
      url: "/repo/openeuler"
      update_rate: "60m"
      includes:
      - "*.rpm"
      - "*.iso"
      excludes:
      json_support: false
      filename_as_id: false
      add_filesize: true
      remove_deleted: true
      add_as_inner_object: false
      store_source: false
      index_content: false
      indexed_chars: "0"
      attributes_support: false
      raw_metadata: false
      xml_support: false
      index_folders: true
      lang_detect: false
      continue_on_error: false
      pdf_ocr: false
    elasticsearch:
      nodes:
      - url: "https://xxxx.xxx.cn:9200"
      index: "openeuler"
      bulk_size: 1000
      flush_interval: "60s"
      byte_size: "10mb"
      username: "<username>"
      password: "<password>"
    rest:
      url: "http://127.0.0.1:8080/fscrawler"
```
It works well only except that the pod will consume lots of memory, this is how it looks when first started:
```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  3.4  0.9 9949236 325612 ?      Ssl  01:57   0:18 /usr/java/openjdk-14/bin/java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8 -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager -cp /fscrawler/lib/* -jar /fscrawler/lib/fscrawler-es7-2.7-SNAPSHOT.jar openeuler
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root        30  0.0  0.0  15260  1852 pts/0    Ss+  01:58   0:00 bash
root       218  0.0  0.0   7780   668 pts/1    S+   02:06   0:00 head -10
root       217  0.0  0.0  26560   924 pts/1    S+   02:06   0:00 sort -rn -k4
root       216  0.0  0.0  55168  1856 pts/1    R+   02:06   0:00 ps auxw
root       178  0.0  0.0  15260  1868 pts/1    Ss   02:06   0:00 bash
```
Is there any way to reduce the memory usage? and what if I set the JVM option "FS_JAVA_OPTS="-Xmx521m -Xms521m" bin/fscrawler" to limit the memory.

**Job Settings**

```yml
FULL FSCrawler Job Settings HERE
```

**Logs**

```
FULL FSCrawler LOGS HERE
```

**Expected behavior**

**Versions:**
 - OS: Used in container
 - Version 2.7

**Attachment**

If the bug is related to a given file, please share this file so we can reuse it in tests
to reproduce the problem and may be use it in our integration tests.
