### ISSUE TITLE
InputStream must have > 0 bytes

### ISSUE THREAD

**Issue by yuanzhian** [dadoonet/fscrawler#1084]
**Describe the bug**

2021-01-21 16:55:34,699 [�[1;31mERROR�[m] [432b55eaff4760a17c1e7b1732b55968][/zcy-m-front-master-dbdc3f8ef600dc07700cf477c8bc521492c54ba2/plop-templates/view/index.less] InputStream must have > 0 bytes

**Job Settings**

```yml
---
name: "test2"
fs:
  url: "/tmp/es"
  update_rate: "15m"
  excludes:
  - "*/~*"
  json_support: false
  filename_as_id: false
  add_filesize: true
  remove_deleted: true
  add_as_inner_object: false
  store_source: false
  index_content: true
  attributes_support: false
  raw_metadata: false
  xml_support: false
  index_folders: true
  lang_detect: false
  continue_on_error: false
  ocr:
    language: "eng"
    enabled: true
    pdf_strategy: "ocr_and_text"
  follow_symlinks: false
elasticsearch:
  nodes:
  - url: "http://10.8.25.140:9200"
  bulk_size: 100
  flush_interval: "5s"
  byte_size: "10mb"
  ssl_verification: true

```

**Logs**

```
2021-01-21 16:55:34,699 [�[1;31mERROR�[m] [432b55eaff4760a17c1e7b1732b55968][/zcy-m-front-master-dbdc3f8ef600dc07700cf477c8bc521492c54ba2/plop-templates/view/index.less] InputStream must have > 0 bytes
```

**Expected behavior**

bin/fscrawler test2

**Versions:**
OS: 10.15.3
Version: fscrawler-es7-2.7-SNAPSHOT

** suggest**
Can I add a configuration and skip the empty file
