### ISSUE TITLE
Documentation Error  - windows file paths in _settings.yaml  "url"

### ISSUE THREAD

**Issue by newschapmj1** [dadoonet/fscrawler#1090]
**Windows setting the file path in _settings.yaml**
fs:
   url

https://fscrawler.readthedocs.io/en/latest/user/tutorial.html#start-fscrawler

**Job Settings**
In _settings.yaml url  windows folders should use double backslashes 
```
eg c:\tmp becomes c:\\tmp
or 
c:\tmp\test1   becomes c:\\tmp\\test1
```
```
url: "c:\\tmp" 
url: "c:\\tmp\test1" 
```

An alternative format is to keep using forward slashes and add a forward slash before the drive letter 

`eg /c:/tmp or /c:/tmp/test1`

```
url: "/c:/tmp" 
url: "/c:/tmp/test1"
```

Documentation error
<--------start -------->
```
name: "resumes"
fs:
  # On Linux
  url: "/path/to/resumes"
  # On Windows
  url: "c:\path\to\resumes"
```
<--------end ----------->

Documentation correction
<--------start----------->
```
name: "resumes"
fs:
  # On Linux
  url: "/path/to/resumes"
  # On Windows
  url: "c:\\path\\to\\resumes"
```

<---------------->

```yml
FULL FSCrawler Job Settings HERE
```

**Logs**
url c:\tmp generates this error
```
06:33:00,788 DEBUG [f.p.e.c.f.FsParserAbstract] Fs crawler thread [test2200] is now running. Run #1...
06:33:00,788 WARN  [f.p.e.c.f.FsParserAbstract] Error while crawling c: mp: c:  mp doesn't exists.
06:33:00,788 WARN  [f.p.e.c.f.FsParserAbstract] Full stacktrace
```

**Expected behavior**

FSCrawler locates the correct windows folder

**Versions:**
 - OS: [Windows]
 - Version [any?, 2.7]

**Attachment**
None
