### ISSUE TITLE
file attributes not being sent to workplace search

### ISSUE THREAD

**Issue by ulysse31** [dadoonet/fscrawler#1107]
**Describe the bug**

Architecture :  linux server crawling over nfs directory, pushing metadata to workplace search.
Expected: having fieds like owner, permissions, etc when attributes_support: true

Result: No owner or permission field present in workplace, with debug enabled, no reference to owner or permission field on logs.

**Job Settings**

```yml
name: "SHARE_TEST"
fs:
  url: "/mnt/SHARE_TEST"
  update_rate: "15m"
  excludes:
  - "*/~*"
  json_support: false
  filename_as_id: false
  add_filesize: true
  remove_deleted: true
  add_as_inner_object: false
  store_source: false
  index_content: true
  raw_metadata: true
  xml_support: false
  index_folders: true
  lang_detect: true
  indexed_chars: "-1"
  continue_on_error: true
  attributes_support: true
  ocr:
    language: "eng"
    enabled: true
    pdf_strategy: "ocr_and_text"
  follow_symlinks: false
elasticsearch:
  nodes:
  - url: "http://es-host.example.com"
  bulk_size: 100
  flush_interval: "5s"
  byte_size: "10mb"
  ssl_verification: true
  username: fscrawler-user
  password: XXXXXXXXXXXXXXXXXXX
workplace_search:
  access_token: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
  key: "XXXXXXXXXXXXXXXXXXXXX"
  server: "https://workplace.example.com"
  url_prefix: "https://dl.example.com/SHARE_TEST"
  bulk_size: 100
  flush_interval: "2s"

```

**Logs**

```
Debug line sample:

14:08:27,177 ESC[36mDEBUGESC[m [f.p.e.c.f.t.w.WPSearchClient] Adding document {extension=pptx, comments=null, keywords=null, author=null, created_at=2021-11-12 13:09:00+01:00, language=, body=, title=.XXX.pptx, url=https://dl.example.com/SHARE_TEST/.XXX.pptx, path=/mnt/SHARE_TEST/Sample/.XXX.pptx, size=4096, text_size=null, mime_type=multipart/appledouble, name=.XXX.pptx, id=xxxxxxxxxxxxxxxxxxxxxxxxxxx, last_modified=2021-11-12 13:09:00+01:00}

```

**Expected behavior**

Expected: having fieds like owner, permissions, etc when attributes_support: true

**Versions:**
 - OS: Linux Debian Buster
 - Version 2.7 SNAPSHOT
