### ISSUE TITLE
FSCrawler Container Starts Jshell and then Restarts

### ISSUE THREAD

**Issue by benbdevd** [dadoonet/fscrawler#1147]
**Describe the bug**

Trying to run Elasticsearch, Kibana, and FSCrawler all as containers.
When I run `docker-compose up`, the FSCrawler container displays a Jshell prompt and restarts over and over.

**Job Settings**

```yml
---
name: "idx"
fs:
  url: "/usr/app/data"
  update_rate: "15m"
  indexed_chars: 100%
  json_support: false
  filename_as_id: false
  add_filesize: true
  remove_deleted: true
  add_as_inner_object: false
  store_source: false
  index_content: true
  attributes_support: false
  raw_metadata: false
  xml_support: false
  index_folders: true
  lang_detect: true
  continue_on_error: false
  ocr:
    language: "eng"
    enabled: true
    pdf_strategy: "ocr_and_text"
  follow_symlinks: false
elasticsearch:
  nodes:
    - url: "http://es01:9200"
  bulk_size: 100
  flush_interval: "5s"
  byte_size: "10mb"
```

**Docker Compose File**

```yml
version: '3'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_VERSION
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms768m -Xmx768m"
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - fscrawler_net

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_VERSION
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms768m -Xmx768m"
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    ports:
      - 9201:9200
    networks:
      - fscrawler_net

  kib01:
    image: docker.elastic.co/kibana/kibana:$ELASTIC_VERSION
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    restart: always
    networks:
      - fscrawler_net

  fscrawler:
    image: dadoonet/fscrawler:2.7-SNAPSHOT-es7-eng
    container_name: fscrawler
    restart: always
    volumes:
      - ./data:/usr/app/data/:ro
      - ./config/:/usr/app/config/
    depends_on:
      - es01
      - es02
      - kib01
#    command: [ "./wait-for-it.sh", "-h es01", "-t 30", "-p 9200" ]
# commented out this line because I couldn't figure out how to copy the shell script into the container
    networks:
      - fscrawler_net

volumes:
  data01:
    driver: local
  data02:
    driver: local

networks:
  fscrawler_net:
    driver: bridge
```

**Logs**

```
fscrawler    | |  Welcome to JShell -- Version 15.0.2
fscrawler    | |  For an introduction type: /help intro
fscrawler    | 
fscrawler    | jshell> fscrawler exited with code 0
fscrawler    | |  Welcome to JShell -- Version 15.0.2
fscrawler    | |  For an introduction type: /help intro
fscrawler    | 
fscrawler    | jshell> fscrawler exited with code 0
fscrawler    | |  Welcome to JShell -- Version 15.0.2
fscrawler    | |  For an introduction type: /help intro
fscrawler    | 
fscrawler    | jshell> fscrawler exited with code 0
```

**Expected behavior**

Expected the container to not exit, and run the FSCrawler program so that I can index my data.

**Versions:**
 - OS: Ubuntu 21.04
 - Version: 2.7-SNAPSHOT-es7-eng Docker image
