### ISSUE TITLE
path.real not set on folders

### ISSUE THREAD

**Issue by MatthiasKuehneEllerhold** [dadoonet/fscrawler#1164]
**Describe the bug**

We want to search for folders in a samba share and Ive set up a file server with spotlight support via this How-To: https://wiki.samba.org/index.php/Spotlight_with_Elasticsearch_Backend

An FSCrawler job is used to index all files and directories into elasticsearch.

Searching via Finder or mdfind only returns files and no directories. Digging into the data FSCrawler creates it seems like path.real is missing.

Example record in ES for a file:
```json
{
        "_index" : "storage2",
        "_type" : "_doc",
        "_id" : "hash",
        "_score" : 1.0,
        "_source" : {
          "meta" : { },
          "file" : {
            "extension" : "pdf",
            "created" : "2020-02-26T18:33:44.000+00:00",
            "last_modified" : "2020-02-26T18:33:44.000+00:00",
            "last_accessed" : "2021-06-08T11:31:37.860+00:00",
            "indexing_date" : "2021-06-09T13:33:35.288+00:00",
            "filename" : "abc.pdf",
            "url" : "file:///storage2/abc.pdf"
          },
          "path" : {
            "root" : "hash",
            "virtual" : "/abc.pdf",
            "real" : "/storage2/abc.pdf"
        }
    }
}
```

Example record in ES for a directory:
```json
{
        "_index" : "storage2_folder",
        "_type" : "_doc",
        "_id" : "hash",
        "_score" : 1.0,
        "_source" : {
          "root" : "hash",
          "virtual" : "/directory",
          "real" : "/storage2/directory"
        }
      }
```

**Job Settings**

```yml
---
name: "storage2"
fs:
  url: "/storage2"
  update_rate: "5m"
  index_folders: true
  continue_on_error: true
  ocr:
    enabled: false
  add_filesize: false
  index_content: false
  json_support: false
  remove_deleted: true
  excludes:
    - "*/~*"
    - "*/.DS_Store"
  filename_as_id: false
  add_as_inner_object: false
  store_source: false
  attributes_support: false
  raw_metadata: false
  xml_support: false
  follow_symlinks: false
  lang_detect: false

elasticsearch:
  nodes:
    - url: "http://127.0.0.1:9200"
  bulk_size: 100
  flush_interval: "5s"
  byte_size: "10mb"
  ssl_verification: false
```

**Logs**

```
,----------------------------------------------------------------------------------------------------.
|       ,---,.  .--.--.     ,----..                                     ,--,            2.7-SNAPSHOT |
|     ,'  .' | /  /    '.  /   /   \                                  ,--.'|                         |
|   ,---.'   ||  :  /`. / |   :     :  __  ,-.                   .---.|  | :               __  ,-.   |
|   |   |   .';  |  |--`  .   |  ;. /,' ,'/ /|                  /. ./|:  : '             ,' ,'/ /|   |
|   :   :  :  |  :  ;_    .   ; /--` '  | |' | ,--.--.       .-'-. ' ||  ' |      ,---.  '  | |' |   |
|   :   |  |-, \  \    `. ;   | ;    |  |   ,'/       \     /___/ \: |'  | |     /     \ |  |   ,'   |
|   |   :  ;/|  `----.   \|   : |    '  :  / .--.  .-. | .-'.. '   ' .|  | :    /    /  |'  :  /     |
|   |   |   .'  __ \  \  |.   | '___ |  | '   \__\/: . ./___/ \:     ''  : |__ .    ' / ||  | '      |
|   '   :  '   /  /`--'  /'   ; : .'|;  : |   ," .--.; |.   \  ' .\   |  | '.'|'   ;   /|;  : |      |
|   |   |  |  '--'.     / '   | '/  :|  , ;  /  /  ,.  | \   \   ' \ |;  :    ;'   |  / ||  , ;      |
|   |   :  \    `--'---'  |   :    /  ---'  ;  :   .'   \ \   \  |--" |  ,   / |   :    | ---'       |
|   |   | ,'               \   \ .'         |  ,     .-./  \   \ |     ---`-'   \   \  /             |
|   `----'                  `---`            `--`---'       '---"                `----'              |
+----------------------------------------------------------------------------------------------------+
|                                        You know, for Files!                                        |
|                                     Made from France with Love                                     |
|                           Source: https://github.com/dadoonet/fscrawler/                           |
|                          Documentation: https://fscrawler.readthedocs.io/                          |
`----------------------------------------------------------------------------------------------------'

Memory [Free/Total=Percent]: HEAP [482.8mb/7.8gb=6.01%], RAM [3.7gb/31.4gb=11.81%], Swap [14.8gb/14.8gb=99.65%].
Starting FS crawler
FS crawler started in watch mode. It will run unless you stop it with CTRL+C.
Elasticsearch Client for version 7.x connected to a node running version 7.13.1
Elasticsearch Client for version 7.x connected to a node running version 7.13.1
FS crawler started for [storage2] for [/storage2] every [5m]
```

**Expected behavior**

High-Level: I want to be able to find directories while using the finder (or mdfind) on a Mac connected to a samba share.
FS-Crawler-specific: I want to have path.real set on a data record of a directory in ElasticSearch.

**Versions:**
 - OS: MacOS 11.4 (Intel) as Client, Debian 10 as Samba-Server
 - FS-Crawler: 2.7-20210505.084329-178
 - ElasticSearch: 7.13.1
