### ISSUE TITLE
Misleading error message on poorly formed _settings.yaml file

### ISSUE THREAD

**Issue by ottadini** [dadoonet/fscrawler#1169]
**Describe the bug**

When there is a typo or some syntax error in the _settings.yaml file for an existing job, fscrawler reports that there is no existing job at the specified config_dir location and asks if you would like to create one. 

**Job Settings**

(note deliberate error: trailing comma in includes option)

```yml
name: "stock"
fs:
  url: "/projects/Work/External/FBC"
  includes : [ "*.doc", "*.xls", "*.docx", "*.xlsx", "*.pdf" ],
  excludes:
  - "*/~*"
  continue_on_error: true
  index_folders: false
  attributes_support: false
  raw_metadata: false
  add_filesize : true
  ignore_above: 250mb
  store_source: false
elasticsearch:
  nodes:
  - url: "http://localhost:9200"
  index: "docs"

```

**Expected behaviour**

fscrawler reports that the job exists but cannot parse the _settings.yaml file. 

**Versions:**
 - OS: linux
 - Version: 2.7 SNAPSHOT
