### ISSUE TITLE
Starting fscrawler with `--rest idx` but a different job-name throws `NoSuchElementException` 

### ISSUE THREAD

**Issue by HansBambel** [dadoonet/fscrawler#1727]
**Describe the bug**

While trying to get fscrawler running with OpenSearch using docker-compose I was toying around with a test-job called `sample_files`.

A part from the relevant `docker-compose.yml`:
```yml
fscrawler:
    image: dadoonet/fscrawler:2.10-SNAPSHOT
    container_name: fscrawler
    restart: always
    volumes:
      - ${PWD}/config:/root/.fscrawler
      - ${PWD}/logs:/usr/share/fscrawler/logs
      - ~/sampleFiles/:/tmp/es:ro
    depends_on:
      - opensearch-node1
    command: fscrawler --rest idx  # <-- this needs to be sample_files to work
    networks:
      - opensearch-net
```

Related issue where this was found:
https://github.com/dadoonet/fscrawler/issues/1274#issuecomment-1764144306

**Job Settings**

```yml
---
name: "sample_files"
elasticsearch:
  nodes:
  - url: "https://opensearch-node1:9200"
  bulk_size: 100
  flush_interval: "5s"
  byte_size: "10mb"
  ssl_verification: false # is true by default
  username: "admin"
  password: "admin"
```

**Logs**

```
 ✔ Container opensearch-node1  Running                                                                                           0.0s
Attaching to fscrawler
fscrawler  | Exception in thread "main" java.util.NoSuchElementException
fscrawler  | 	at java.base/java.util.Scanner.throwFor(Scanner.java:937)
fscrawler  | 	at java.base/java.util.Scanner.next(Scanner.java:1478)
fscrawler  | 	at fr.pilato.elasticsearch.crawler.fs.cli.FsCrawlerCli.main(FsCrawlerCli.java:254)
```

**Expected behavior**

An error message that the given job-name was not found or does not exist instead of the `NoSuchElementException`.

**Versions:**
 - OS: MacOS
 - Version: 13.6

**Attachment**

It seems to be from the [line](https://github.com/dadoonet/fscrawler/blob/35b58e1bd939fbbcdaf7f55e86ca81540ecd624a/cli/src/main/java/fr/pilato/elasticsearch/crawler/fs/cli/FsCrawlerCli.java#L254C40-L254C40) with the following context:

```
FSCrawlerLogger.console("job [{}] does not exist", jobName);

String yesno = null;
while (!"y".equalsIgnoreCase(yesno) && !"n".equalsIgnoreCase(yesno)) {
    FSCrawlerLogger.console("Do you want to create it (Y/N)?");
    yesno = scanner.next();
}
```
