### ISSUE TITLE
Error in _settings.yaml doesn't throw an error on job startup, instead I'm asked if the _settings file should be created

### ISSUE THREAD

**Issue by abeaudin** [dadoonet/fscrawler#1767]
**Describe the bug**

I mis-formatted the` _settings.yaml` and on the job start up, rather that logging that there's an error with the yaml file format, I get  the 

```
"job [jobname] does not exist"
"Do you want to create it (Y/N)?" 
```

```sh
cat _settings.yaml
```

```yml
elasticsearch:
  nodes:
  - url: "https://---------"
  username: "elastic"
  password: "-----------"
  bulk_size: 100
  flush_interval: "5s"
  byte_size: "10mb"
  ssl_verification: true
 workplace_search:
   name: "DemoSource"
   id: "---------------"
   server: "https://------------------"
   api_key: "--------------------"
```

Removing the space in front of the workplace_search:  fixes the yaml format and the job starts properly.

**Job Settings**

```yml
elasticsearch:
  nodes:
  - url: "https://---------"
  username: "elastic"
  password: "-----------"
  bulk_size: 100
  flush_interval: "5s"
  byte_size: "10mb"
  ssl_verification: true
 workplace_search:
   name: "DemoSource"
   id: "---------------"
   server: "https://------------------"
   api_key: "--------------------"
```

**Logs**

```
19:51:18,073 INFO  [f.p.e.c.f.c.BootstrapChecks] Memory [Free/Total=Percent]: HEAP [92.8mb/1.8gb=4.8%], RAM [168.4mb/7.5gb=2.18%], Swap [1.3gb/1.9gb=69.46%].
19:51:18,277 INFO  [f.console] job [WOT] does not exist
19:51:18,277 INFO  [f.console] Do you want to create it (Y/N)?
```

**Expected behavior**

I'd expect a parsing error which would point me to go fix the file, instead it's the Do you want to create message instead.

**Versions:**
 - OS: [Ubuntu host running docker]
 - Version [2.10-SNAPSHOT]

**Attachment**
