### ISSUE TITLE
Crawler mixes up content from different files

### ISSUE THREAD

**Issue by j-a-a-p** [dadoonet/fscrawler#1798]
**Describe the bug**
An empty document is crawled, the content and file node in the index are filled with the data of probably the previous parsed document.
This bug is a combination of another bug, documents starting with ~ are being included. In our text corpus it is going through.

**Job Settings**

```yml
# required
name: "abc"

# required
fs:
  # define a "local" file path crawler, if running inside a docker container this must be the path INSIDE the container
  url: "/tmp/es"
  follow_symlink: false
  remove_deleted: false
  continue_on_error: true
  update_rate: "5m"
  includes:
  - "*.pdf"
  - "*.doc"
  - "*.docx"
  - "*.xsl"
  - "*.xslx"
  - "*.msg"
  - "*.txt"
  - "*.md"
  excludes:
  - "*.exclude"
  - "~*"
  # optional: do not send big files to TIKA
  ignore_above: "512mb"

  # special handling of JSON files, should only be used if ALL files are JSON
  json_support: false
  add_as_inner_object: false
  xml_support: false
  filename_as_id: false
  add_filesize: true
  # inlcude user/group of file only if needed
  attributes_support: false
  # do you REALLY want to store every file as a copy in the index ? Then set this to true
  store_source: false
  # you may want to store (partial) content of the file (see indexed_chars)
  index_content: true
  # how much data from the content of the file should be indexed (and stored inside the index), set to 0 if you need checksum, but no content at all to be indexed
  #indexed_chars: "0"
  # TODO what is the tradeoff here, if set to 0 all seems to work still
  indexed_chars: "1000000"
  # usually file metadata will be stored in separate fields, if you want to keep the original set, set this to true
  raw_metadata: false
  # optional: add checksum meta (requires index_content to be set to true)
  checksum: "MD5"
  # recommmended, but will create another index
  index_folders: false
  lang_detect: true

  ocr.pdf_strategy: noocr
  #ocr:
  #  language: "eng"
  #  path: "/path/to/tesseract/if/not/available/in/PATH"
  #  data_path: "/path/to/tesseract/tessdata/if/needed"

# optional: only required if you want to SSH to another server to index documents from there
#server:
#  hostname: "localhost"
#  port: 22
#  username: "dadoonet"
#  password: "password"
#  protocol: "SSH"
#  pem_path: "/path/to/pemfile"

# required
elasticsearch:
  nodes:
  # With Cloud ID
  # - cloud_id: "CLOUD_ID"
  # With URL
  - url: "https://es01.localhost.direct:9200"
  bulk_size: 1000
  flush_interval: "5s"
  byte_size: "10mb"
  username: "elastic"
  password: "changeme"
  # optional, defaults to "docs"
  index: "tldr_index_docs"
  # optional, defaults to "test_folders", used when es.index_folders is set to true
  # index_folder: "test_fold"
  ssl_verification: true
  pipeline: "fscrawler"
rest:
  # only is started with --rest option
  url: "http://localhost:8080/fscrawler"
  enable_cors: true
```

**Logs**

```
FULL FSCrawler LOGS HERE
```

**Expected behavior**
Make sure data of files are not being mixed up.

**Versions:**
Mac
version 10

**Attachment**

If the bug is related to a given file, please share this file, so we can reuse it in tests
to reproduce the problem and may be use it in our integration tests.
