### ISSUE TITLE
Support for noob_ FSCrawler on Docker compose

### ISSUE THREAD

**Issue by shouari** [dadoonet/fscrawler#1843]
While running the FSCrawler o via docker compose, I face this error.
`2024-03-25 17:47:19 21:47:19,717 ERROR [f.p.e.c.f.c.FsCrawlerCli] job [doc_idx] does not exist. Exiting as we are in silent mode or no input available.`

Here is `_settings`:

```
name: "doc_idx"
fs:
  indexed_chars: 100%
  lang_detect: true
  continue_on_error: true
  ocr:
    language: "eng"
    enabled: true
    pdf_strategy: "ocr_and_text"
elasticsearch:
  nodes:
    - url: "https://elasticsearch:9200"
  username: "elastic"
  password: "a123456"
  ssl_verification: false
rest :
  url: "http://fscrawler:8080"
```

and here is the `docker-compose` file fscrawler section

```
fscrawler:
    image: dadoonet/fscrawler:$FSCRAWLER_VERSION
    container_name: fscrawler
    restart: always
    volumes:
      - ../../test-documents/src/main/resources/documents/:/tmp/es:ro
      - ${PWD}/config:/root/.fscrawler
      - ${PWD}/logs:/usr/share/fscrawler/logs
      - ${PWD}/external:/usr/share/fscrawler/external
    depends_on:
      elasticsearch:
         condition: service_healthy
    ports: 
      - ${FSCRAWLER_PORT}:8080
    command: fscrawler doc_idx --restart --rest
```

Can you please help with this?

**Comment by dadoonet** [comment]
Where exactly did you put the job settings?

**Comment by shouari** [comment]
here is the structure I used

> .
> ├── config
> │   └── documents_search
> │       └── _settings.yaml
> ├── data
> │   └── Files to index
> ├── logs
> │   └── Empty folder so far
> └── docker-compose.yml
> └── .env

**Comment by dadoonet** [comment]
You need to change this line:

    command: fscrawler doc_idx --restart --rest
    
To

    command: fscrawler documents_search --restart --rest
    
    
Also note that you might have to change the name setting 

    name: "doc_idx"
    
To

    name: "documents_search"

**Comment by shouari** [comment]
I did the mods above, but still the same error:

`2024-03-26 16:06:59 20:06:59,762 ERROR [f.p.e.c.f.c.FsCrawlerCli] job [documents_search] does not exist. Exiting as we are in silent mode or no input available`.

**Comment by dadoonet** [comment]
Could you share the full logs and switch to trace mode?

**Comment by dadoonet** [comment]
May be try this:

```
command: fscrawler documents_search --trace --restart --rest
```

**Comment by shouari** [comment]
Sure here they are:

`_settings.yaml`
> ---

> name: "documents_search"
> fs:
>   url: "C:\Users\shouari\Documents\Documentation_es\data"
>   indexed_chars: 100%
>   lang_detect: true
>   continue_on_error: true
>   ocr:
>     language: "eng+fra"
>     enabled: true
>     pdf_strategy: "ocr_and_text"
> elasticsearch:
>   nodes:
>     - url: "https://elasticsearch:9200"
>   username: "elastic"
>   password: "a123456"
>   ssl_verification: false
> rest :
>   url: "http://fscrawler:8080"

`docker-compose.yaml`

> 'version: "2.2"
> services:
>   
>   setup:
>     image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
>     volumes:
>       - certs:/usr/share/elasticsearch/config/certs
>     user: "0"
>     command: >
>       bash -c '
>         if [ x${ELASTIC_PASSWORD} == x ]; then
>           echo "Set the ELASTIC_PASSWORD environment variable in the .env file";
>           exit 1;
>         elif [ x${KIBANA_PASSWORD} == x ]; then
>           echo "Set the KIBANA_PASSWORD environment variable in the .env file";
>           exit 1;
>         fi;
>         if [ ! -f certs/ca.zip ]; then
>           echo "Creating CA";
>           bin/elasticsearch-certutil ca --silent --pem -out config/certs/ca.zip;
>           unzip config/certs/ca.zip -d config/certs;
>         fi;
>         if [ ! -f certs/certs.zip ]; then
>           echo "Creating certs";
>           echo -ne \
>           "instances:\n"\
>           "  - name: elasticsearch\n"\
>           "    dns:\n"\
>           "      - elasticsearch\n"\
>           "      - localhost\n"\
>           "    ip:\n"\
>           "      - 127.0.0.1\n"\
>           > config/certs/instances.yml;
>           bin/elasticsearch-certutil cert --silent --pem -out config/certs/certs.zip --in config/certs/instances.yml --ca-cert config/certs/ca/ca.crt --ca-key config/certs/ca/ca.key;
>           unzip config/certs/certs.zip -d config/certs;
>         fi;
>         echo "Setting file permissions"
>         chown -R root:root config/certs;
>         find . -type d -exec chmod 750 \{\} \;;
>         find . -type f -exec chmod 640 \{\} \;;
>         echo "Waiting for Elasticsearch availability";
>         until curl -s --cacert config/certs/ca/ca.crt https://elasticsearch:9200 | grep -q "missing authentication credentials"; do sleep 30; done;
>         echo "Setting kibana_system password";
>         until curl -s -X POST --cacert config/certs/ca/ca.crt -u elastic:${ELASTIC_PASSWORD} -H "Content-Type: application/json" https://elasticsearch:9200/_security/user/kibana_system/_password -d "{\"password\":\"${KIBANA_PASSWORD}\"}" | grep -q "^{}"; do sleep 10; done;
>         echo "All done!";
>       '
>     healthcheck:
>       test: ["CMD-SHELL", "[ -f config/certs/elasticsearch/elasticsearch.crt ]"]
>       interval: 1s
>       timeout: 5s
>       retries: 120
> 
>   elasticsearch:
>     depends_on:
>       setup:
>         condition: service_healthy
>     image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
>     volumes:
>       - certs:/usr/share/elasticsearch/config/certs
>       - esdata:/usr/share/elasticsearch/data
>     ports:
>       - ${ES_PORT}:9200
>     environment:
>       - node.name=elasticsearch
>       - cluster.name=${CLUSTER_NAME}
>       - cluster.initial_master_nodes=elasticsearch
>       - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
>       - bootstrap.memory_lock=true
>       - xpack.security.enabled=true
>       - xpack.security.http.ssl.enabled=true
>       - xpack.security.http.ssl.key=certs/elasticsearch/elasticsearch.key
>       - xpack.security.http.ssl.certificate=certs/elasticsearch/elasticsearch.crt
>       - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
>       - xpack.security.http.ssl.verification_mode=certificate
>       - xpack.security.transport.ssl.enabled=true
>       - xpack.security.transport.ssl.key=certs/elasticsearch/elasticsearch.key
>       - xpack.security.transport.ssl.certificate=certs/elasticsearch/elasticsearch.crt
>       - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
>       - xpack.security.transport.ssl.verification_mode=certificate
>       - xpack.license.self_generated.type=${LICENSE}
>     mem_limit: ${MEM_LIMIT}
>     ulimits:
>       memlock:
>         soft: -1
>         hard: -1
>     healthcheck:
>       test:
>         [
>           "CMD-SHELL",
>           "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
>         ]
>       interval: 10s
>       timeout: 10s
>       retries: 120
> 
>   kibana:
>     depends_on:
>       elasticsearch:
>         condition: service_healthy
>     image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
>     volumes:
>       - certs:/usr/share/kibana/config/certs
>       - kibanadata:/usr/share/kibana/data
>     ports:
>       - ${KIBANA_PORT}:5601
>     environment:
>       - SERVERNAME=kibana
>       - ELASTICSEARCH_HOSTS=https://elasticsearch:9200
>       - ELASTICSEARCH_USERNAME=kibana_system
>       - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
>       - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt
>       - ENTERPRISESEARCH_HOST=http://localhost:${ENTERPRISE_SEARCH_PORT}
>     mem_limit: ${MEM_LIMIT}
>     healthcheck:
>       test:
>         [
>           "CMD-SHELL",
>           "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
>         ]
>       interval: 10s
>       timeout: 10s
>       retries: 120
> 
> 
>   '# FSCrawler
>   fscrawler:
>     image: dadoonet/fscrawler:$FSCRAWLER_VERSION
>     container_name: fscrawler
>     restart: always
>     volumes:
>       - ../../test-documents/src/main/resources/documents/:/tmp/es:ro
>       - ${PWD}/config:/root/.fscrawler
>       - ${PWD}/logs:/usr/share/fscrawler/logs
>       - ${PWD}/external:/usr/share/fscrawler/external
>     depends_on:
>       elasticsearch:
>          condition: service_healthy
>     ports: 
>       - ${FSCRAWLER_PORT}:8080
>     command: fscrawler documents_search --trace --restart --rest
> volumes:
>   certs:
>     driver: local
>   '# enterprisesearchdata:
>  ' #   driver: local
>   esdata:
>     driver: local
>   kibanadata:
>     driver: local

**Comment by dadoonet** [comment]
Try this:

```
---
name: "documents_search"
fs:
  url: "C:\\Users\\shouari\\Documents\\Documentation_es\\data"
  indexed_chars: 100%
  lang_detect: true
  continue_on_error: true
  ocr:
    language: "eng+fra"
    enabled: true
    pdf_strategy: "ocr_and_text"
elasticsearch:
  nodes:
    - url: "https://elasticsearch:9200"
  username: "elastic"
  password: "a123456"
  ssl_verification: false
rest :
  url: "http://fscrawler:8080"
```

**Comment by shouari** [comment]
I still face the same issue,

I'll have a look at the `/root/.fscrawler/config` as suggested and check for the `documents_search` folder..

If it does not exist, what might be the cause according to you?

**Comment by madlink** [comment]
Hi, 
I'm having the same issue

_settings.yml
`name: "ingest_documents"
fs:
  indexed_chars: 100%
  lang_detect: true
  continue_on_error: true
  ocr:
    language: "eng"
    enabled: true
    pdf_strategy: "ocr_and_text"
elasticsearch:
  nodes:
    - url: "http://es01:9200"
  username: "elastic"
  password: "elastic"
  ssl_verification: false
  index: "pen_poc"
rest:
  url: "http://fscrawler:8080"
`
Log with trace
`18:16:32,938 [33mWARN [m [f.p.e.c.f.c.FsCrawlerCli] --trace option has been deprecated. Use FS_JAVA_OPTS="-DLOG_LEVEL=trace" instead.
18:16:32,966 [32mINFO [m [f.console] ,----------------------------------------------------------------------------------------------------.
|       ,---,.  .--.--.     ,----..                                     ,--,           2.10-SNAPSHOT |
|     ,'  .' | /  /    '.  /   /   \                                  ,--.'|                         |
|   ,---.'   ||  :  /`. / |   :     :  __  ,-.                   .---.|  | :               __  ,-.   |
|   |   |   .';  |  |--`  .   |  ;. /,' ,'/ /|                  /. ./|:  : '             ,' ,'/ /|   |
|   :   :  :  |  :  ;_    .   ; /--` '  | |' | ,--.--.       .-'-. ' ||  ' |      ,---.  '  | |' |   |
|   :   |  |-, \  \    `. ;   | ;    |  |   ,'/       \     /___/ \: |'  | |     /     \ |  |   ,'   |
|   |   :  ;/|  `----.   \|   : |    '  :  / .--.  .-. | .-'.. '   ' .|  | :    /    /  |'  :  /     |
|   |   |   .'  __ \  \  |.   | '___ |  | '   \__\/: . ./___/ \:     ''  : |__ .    ' / ||  | '      |
|   '   :  '   /  /`--'  /'   ; : .'|;  : |   ," .--.; |.   \  ' .\   |  | '.'|'   ;   /|;  : |      |
|   |   |  |  '--'.     / '   | '/  :|  , ;  /  /  ,.  | \   \   ' \ |;  :    ;'   |  / ||  , ;      |
|   |   :  \    `--'---'  |   :    /  ---'  ;  :   .'   \ \   \  |--" |  ,   / |   :    | ---'       |
|   |   | ,'               \   \ .'         |  ,     .-./  \   \ |     ---`-'   \   \  /             |
|   `----'                  `---`            `--`---'       '---"                `----'              |
+----------------------------------------------------------------------------------------------------+
|                                        You know, for Files!                                        |
|                                     Made from France with Love                                     |
|                           Source: https://github.com/dadoonet/fscrawler/                           |
|                          Documentation: https://fscrawler.readthedocs.io/                          |
`----------------------------------------------------------------------------------------------------'

18:16:32,978 [32mINFO [m [f.p.e.c.f.c.BootstrapChecks] Memory [Free/Total=Percent]: HEAP [494.7mb/7.8gb=6.17%], RAM [22.6gb/31.3gb=72.52%], Swap [7.6gb/8gb=95.59%].
18:16:32,982 [36mDEBUG[m [f.p.e.c.f.f.FsCrawlerUtil] Mapping [6/_settings.json] already exists
18:16:32,984 [36mDEBUG[m [f.p.e.c.f.f.FsCrawlerUtil] Mapping [6/_settings_folder.json] already exists
18:16:32,985 [36mDEBUG[m [f.p.e.c.f.c.FsCrawlerCli] Cleaning existing status for job [ingest_documents]...
18:16:32,986 [30mTRACE[m [f.p.e.c.f.f.MetaFileHandler] Removing file _status.json from /root/.fscrawler/ingest_documents if exists
18:16:32,988 [36mDEBUG[m [f.p.e.c.f.c.FsCrawlerCli] Starting job [ingest_documents]...
18:16:32,989 [30mTRACE[m [f.p.e.c.f.f.MetaFileHandler] Reading file _settings.yaml from /root/.fscrawler/ingest_documents
18:16:32,990 [30mTRACE[m [f.p.e.c.f.f.MetaFileHandler] Reading file _settings.json from /root/.fscrawler/ingest_documents
18:16:32,992 [36mDEBUG[m [f.p.e.c.f.c.FsCrawlerCli] job [ingest_documents] does not exist.
18:16:32,992 [1;31mERROR[m [f.p.e.c.f.c.FsCrawlerCli] job [ingest_documents] does not exist. Exiting as we are in silent mode or no input available.`


Compose: 
`version: "3.9"

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    labels:
      co.elastic.logs/module: elasticsearch
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - ${ES_PORT}:9200
    environment:
      - node.name=es01
      - cluster.name=${CLUSTER_NAME}
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - bootstrap.memory_lock=true
      - xpack.license.self_generated.type=${LICENSE}
      #- ES_JAVA_OPTS=-Xms2g -Xmx2g
    mem_limit: ${ES_MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt http://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
    networks:
      - elastic
    restart: unless-stopped

  # FSCrawler
  fscrawler:
    image: dadoonet/fscrawler:$FSCRAWLER_VERSION
    container_name: fscrawler
    restart: always
    volumes:
      - ./config:/root/.fscrawler
      - ./logs:/usr/share/fscrawler/logs
      - ./external:/usr/share/fscrawler/external
    depends_on:
      es01:
        condition: service_healthy
    ports:
      - ${FSCRAWLER_PORT}:8080
    command: fscrawler ingest_documents --trace --restart --rest # ingest_documents --restart --rest
    networks:
      - elastic

networks:
  elastic:
    driver: bridge

volumes:
  esdata01:
    driver: local
`
Folder structure
![image](https://github.com/dadoonet/fscrawler/assets/752386/38d256a9-eb7e-46c6-bfef-790e1dd41f3c)

from the log it seems the file is present

**Comment by madlink** [comment]
I'm having the same issue, is in the folder:
[fscrawler.log](https://github.com/user-attachments/files/15827037/fscrawler.log)

```
18:22:41,581 [32mINFO [m [f.p.e.c.f.c.BootstrapChecks] Memory [Free/Total=Percent]: HEAP [493.7mb/7.8gb=6.16%], RAM [22.6gb/31.3gb=72.48%], Swap [7.6gb/8gb=95.46%].
18:22:41,586 [36mDEBUG[m [f.p.e.c.f.f.FsCrawlerUtil] Mapping [6/_settings.json] already exists
18:22:41,590 [36mDEBUG[m [f.p.e.c.f.f.FsCrawlerUtil] Mapping [6/_settings_folder.json] already exists
18:22:41,590 [36mDEBUG[m [f.p.e.c.f.c.FsCrawlerCli] Cleaning existing status for job [ingest_documents]...
18:22:41,591 [30mTRACE[m [f.p.e.c.f.f.MetaFileHandler] Removing file _status.json from /root/.fscrawler/ingest_documents if exists
18:22:41,594 [36mDEBUG[m [f.p.e.c.f.c.FsCrawlerCli] Starting job [ingest_documents]...
18:22:41,595 [30mTRACE[m [f.p.e.c.f.f.MetaFileHandler] Reading file _settings.yaml from /root/.fscrawler/ingest_documents
18:22:41,596 [30mTRACE[m [f.p.e.c.f.f.MetaFileHandler] Reading file _settings.json from /root/.fscrawler/ingest_documents
18:22:41,599 [36mDEBUG[m [f.p.e.c.f.c.FsCrawlerCli] job [ingest_documents] does not exist.
18:22:41,599 [1;31mERROR[m [f.p.e.c.f.c.FsCrawlerCli] job [ingest_documents] does not exist. Exiting as we are in silent mode or no input available.
```

```
# FSCrawler
  fscrawler:
    image: dadoonet/fscrawler:$FSCRAWLER_VERSION
    container_name: fscrawler
    restart: always
    volumes:
      - ./config:/root/.fscrawler
      - ./logs:/usr/share/fscrawler/logs
      - ./external:/usr/share/fscrawler/external
    depends_on:
      es01:
        condition: service_healthy
    ports:
      - ${FSCRAWLER_PORT}:8080
    command: fscrawler ingest_documents --trace --restart --rest # ingest_documents --restart --rest
    networks:
      - elastic
```

```
---
name: "ingest_documents"
fs:
  indexed_chars: 100%
  lang_detect: true
  continue_on_error: true
  ocr:
    language: "eng"
    enabled: true
    pdf_strategy: "ocr_and_text"
elasticsearch:
  nodes:
    - url: "http://es01:9200"
  username: "elastic"
  password: "elastic"
  ssl_verification: false
  index: "pen_poc"
rest:
  url: "http://fscrawler:8080"

```

Folder structure: 
![image](https://github.com/dadoonet/fscrawler/assets/752386/d895d54a-fc38-46b1-948c-90aaba260f6b)
