### ISSUE TITLE
Starting FScrawler disrupts Nginx server, users get "502 Bad gateway"

### ISSUE THREAD

**Issue by Sfeeen** [dadoonet/fscrawler#1863]
**Describe the bug**

I use FScrawler on a linux system with Ubuntu in a virtual machine. On this machine runs also a webserver making use of Nginx, gunicorn and flask. 
When I run the command to start the fscrawler: 
./fscrawler zdrive_index --reset --loop 1 the webserver doesn't seem to work normally anymore. Navigating to the website results in "502 bad gateway".

Interupting the crawler terminates the issue.
Checking the services during the problem:
 sudo  systemctl status app
sudo systemctl status nginx

They all are running and seem ok. 
I have no clue but in a way FScrawler seems to interfere with this webserver.

What is remarking is the the issue only happens when adding the "--reset" argument.

**Versions:**
 - OS: Ubuntu LTS
 - FScrawler: 2.10

Exact command line: 
`./fscrawler zdrive_index --restart --loop 1 > zdrivecrawl.log 2>&1`

_settings.yaml:

```
name: "zdrive_index"
fs:
  url: "/home/abc_indexer/Zdrive/"
  update_rate: "15m"
  json_support: false
  filename_as_id: false
  add_filesize: true
  remove_deleted: true
  add_as_inner_object: false
  store_source: false
  index_content: true
  attributes_support: false
  raw_metadata: false
  xml_support: false
  index_folders: true
  lang_detect: false
  continue_on_error: true
  ocr:
    language: "eng"
    enabled: false
    pdf_strategy: "ocr_and_text"
  follow_symlinks: false
elasticsearch:
  nodes:
  - url: "http://127.0.0.1:9200"
  bulk_size: 100
  flush_interval: "5s"
  byte_size: "10mb"
  ssl_verification: true
```
