### ISSUE TITLE
ocr path is wrong in 2 cases: image and pdf

### ISSUE THREAD

**Issue by tukao89** [dadoonet/fscrawler#1988]
**Describe the bug**

When i set ocr path as bellow (end with tesseract.exe), it'll correct with pdf file.

**Job Settings**

```yml
  ocr:
    enabled: true
    path: "C:\\Program Files\\Tesseract-OCR\\tesseract.exe"
    data_path: "C:\\Program Files\\Tesseract-OCR\\tessdata"
    pdf_strategy: "ocr_and_text"
    language: "vie+eng"
    output_type: "txt"
```

But it's not working for image files (example .png). So i changed ocr path as bellow (remove tesseract.exe):

```yml
  ocr:
    enabled: true
    path: "C:\\Program Files\\Tesseract-OCR\\"
    data_path: "C:\\Program Files\\Tesseract-OCR\\tessdata"
    pdf_strategy: "ocr_and_text"
    language: "vie+eng"
    output_type: "txt"
```
==> It's error for pdf file.

**Logs**

```
2024-12-09 16:06:30,950 [ERROR] [test-ocr.pdf][\test-ocr.pdf] Unable to extract PDF content -> Unable to end a page -> I regret that I couldn't find an OCR parser to handle image/ocr-png.Please set the OCR_STRATEGY to NO_OCR or configure yourOCR parser correctly
```

**Versions:**
 - OS: Windows
 - Version 2.10
