### ISSUE TITLE
OCR settings being ignored

### ISSUE THREAD

**Issue by budachst** [dadoonet/fscrawler#758]
**Describe the bug**

Although I have ocr set disable in my job options file, fscrawler is still running tesseract on pdf files it encounters while scanning. Further more, ocs is done with default settings, instead of the setting provided in the jobfile:

```
root     29857  6120  0 09:46 pts/3    00:00:00 tesseract /tmp/apache-tika-6540379283841536434.tmp /tmp/apache-tika-87294301792944645.tmp -l eng --psm 1 -c page_separator= -c preserve_interword_spaces=0 txt
```

Jobfile goes as this:

```
ocr:
  enabled: false
  language: "de"
  pdf_strategy: "no_ocr"
```

**Versions:**
 - fscrawler-es6-2.7-20190528.081956-40
 - CentOS Linux 7.6

**Comment by budachst** [comment]
Ok, looks like Tika triggers tesseract also for images embedded into office dokuments… this explains, why I am still seeing tesseract being run, even when disabling OCR and excluding all graphics files like .png, .jpg snd so on.

Since fscrawler is calling Tika, would it be possible to have Tika being run with it's OCR option disabled, or is Tika setup at job startup using a config for the entire runtime of the fscrawler job?
Also, maybe another control, that disables Tika's OCR at startup would also be a good idea.

My goal is to have first run which will only index all files, without performing anx OCR at all. I could get a quite solid index and have fscrawler take care of the OCR stuff in subsequent runs.

**Comment by dadoonet** [comment]
Yeah. I agree that is looking like a bug to me. 
I mean that if `ocr.enabled` is `false`, we should disable this feature for every type of document. I'll look into this.

I wonder if a workaround could be to indicate a wrong path for OCR application? With https://fscrawler.readthedocs.io/en/latest/user/ocr.html#ocr-path

**Comment by budachst** [comment]
I can try that, but I wonder what Tika will do, if it cannot find tesseract at that location. Will it just continue indexiing the document it currently processes, or will it simply fail and return nothing?

If fscrawler sets up Tika once for the entirety of the job, than you should be ablet to disable Tika's internal OCR using this setup:

```
<?xml version="1.0" encoding="UTF-8"?>
<properties>
  <parsers>
    <parser class="org.apache.tika.parser.DefaultParser">
      <parser-exclude class="org.apache.tika.parser.ocr.TesseractOCRParser"/>
    </parser>
  </parsers>
</properties>
```
I also think that this explains, why Tika runs tesseract with the default language, instead of the language setup in the fscrawler jobfile… at least, this would make sense to me.

**Comment by dadoonet** [comment]
I agree with the setup you proposed. But I'm excluding OCR normally with this line: https://github.com/dadoonet/fscrawler/blob/master/tika/src/main/java/fr/pilato/elasticsearch/crawler/fs/tika/TikaInstance.java#L86

So this looks like a bug to me.
Any chance you could share a document I can use in my integration tests then?

**Comment by budachst** [comment]
Yeah, but I don't see, how you disable the OCR parser in line 86. Looks the opposite to me, actually.
I have also just for fun renamed the tesseract binary, such as that Tika can't find it anymore. This of course effectively, disables tesseract. I will prepare a liitle test with mixed office documents and see, if I can confirm my assumptions. If I can , I will get you some documents for your integration tests.

**Comment by dadoonet** [comment]
Line 86 is about the parsers you want to exclude. See https://tika.apache.org/1.20/api/org/apache/tika/parser/DefaultParser.html#DefaultParser-org.apache.tika.mime.MediaTypeRegistry-org.apache.tika.config.ServiceLoader-java.util.Collection-

**Comment by budachst** [comment]
Ha ha - forgive my ignorance, I am not a developer and I don't know enough about that, but I thought that somewhere in that line, I'd need to see a reference to "exclude".  My java is a bit rusty, but it seems to me that if you disable the TesseractOCRParser class in line 86, you'd also disable the PDRParser class in line 99 in case fs.getOcr().isEnabled() is set to true?

Again, please forgive me, if I am just not seeing it. ;)

**Comment by dadoonet** [comment]
That's true. But the PDFParser is added manually with this line: https://github.com/dadoonet/fscrawler/blob/master/tika/src/main/java/fr/pilato/elasticsearch/crawler/fs/tika/TikaInstance.java#L102

**Comment by budachst** [comment]
Ok, I see… you're calling the Tika DefaultParser constructor without providing the encodingDetector  which is the "2nd" constructor on the page you referenced. Then you create an instance of AutodetectParser with the modified list or parsers - I get that.

However, further down, you seem to configure the language setting only, if fs.getOcr().isEnabled() is true and that would actually explain, why I was seeing tesseract being run with the default language, when I had set fs.getOcr().isEnabled() to false, but Tika called tesseract nevertheless.

So, the question seems to be, why Tika still calls TesseractOCRParser, even if that parser has been disabled.

**Comment by dadoonet** [comment]
> So, the question seems to be, why Tika still calls TesseractOCRParser, even if that parser has been disabled.

Yes. That's the question. And that's why I'd like to reproduce the problem when I have some spare time and try to fix this if possible.

**Comment by budachst** [comment]
I have just tested the workaround to rename tesseract to /usr/bin/renamed_tesseract (yeah, not that genuine, but..) and tried using that in one of my jobfiles:

```
ocr:
  enabled: true
  language: "de"
  pdf_strategy: "ocr_and_text"
  path: "/usr/bin/renamed_tesseract"
```

However, fscrawler/Tika doesn't seem to find it:

```
12:53:39,872 DEBUG [f.p.e.c.f.t.TikaInstance] OCR is activated.
12:53:39,882 DEBUG [f.p.e.c.f.t.TikaInstance] But Tesseract is not installed so we won't run OCR.
12:53:40,323 WARN  [o.a.t.p.PDFParser] J2KImageReader not loaded. JPEG2000 files will not be processed.
See https://pdfbox.apache.org/2.0/dependencies.html#jai-image-io
for optional dependencies.

12:53:40,494 DEBUG [f.p.e.c.f.t.TikaInstance] OCR is activated so we need to configure Tesseract in case we have specific settings.
12:53:40,495 DEBUG [f.p.e.c.f.t.TikaInstance] Tesseract Language set to [eng].
12:53:42,046 DEBUG [f.p.e.c.f.FsParserAbstract] Indexing tr1206570/96d64b3beb2dbf3ad778f318c287fa2?pipeline=null
12:53:42,047 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] computeVirtualPathName(/tr1206570Data/314155, /tr1206570Data/314155/Allgemeine_Kundeninfos/LMA/171020_LMA_SparkasseVorpommern.pdf) = /Allgemeine_Kundeninfos/LMA/171020_LMA_SparkasseVorpommern.pdf
```
Shouldn't it apply the above settings from the jobconfig file?

**Comment by dadoonet** [comment]
I'm confused. Why did you enable ocr? 

I was proposing something like:

```yaml
ocr:
  enabled: false
  path: "/usr/bin/renamed_tesseract"
```

**Comment by dadoonet** [comment]
Any chance you could provide a sample file?

**Comment by budachst** [comment]
I guess, I was confused, since none of the tesseract options ever got sent to tesseract, regardless of what I put into the jobfile.
 I must have tried every combination possible, but e.g. the language settings never showed up in Tesseract's options, when viewing it using ps -ef.

I am currently performing a re-setup of my test server and when I have done that, I will be able to tackle that again.

**Comment by budachst** [comment]
So, after rebuilding my server from scratch, I tried indexing again using the settings, you suggested and with the tesseract binary renamed to "renamed_tesseract", which can be found on the path.

I then fired up the job and tesseract didn't get called…

```
[root@tr1206570 jobs]# which renamed_tesseract
/usr/bin/renamed_tesseract
[root@tr1206570 jobs]# cat tr1206570_352009/_settings.yaml
---
name: "tr1206570_352009"
fs:
  url: "/tr1206570Data/352009"
  update_rate: "15m"
  excludes:
  - "*/~*"
  json_support: false
  filename_as_id: false
  add_filesize: true
  remove_deleted: true
  add_as_inner_object: false
  store_source: false
  index_content: true
  attributes_support: false
  raw_metadata: false
  xml_support: false
  index_folders: true
  lang_detect: false
  continue_on_error: false
  ocr:
    language: "deu"
    enabled: false
    path: "/usr/bin/renamed_tesseract"
    pdf_strategy: "ocr_and_text"
  follow_symlinks: false
elasticsearch:
  nodes:
  - url: "http://10.11.24.116:9200"
  bulk_size: 100
  flush_interval: "5s"
  byte_size: "10mb"
  index: "tr1206570"
  index_folder: "tr1206570"
```

I will now try that once more, enabling ocr and see, whether tesseract gets called using the params I set in the jobfile… hold on…

If I enable ocr in the jobfile and run the job, I am getting this:

```
19:31:24,111 DEBUG [f.p.e.c.f.t.TikaInstance] OCR is activated.
19:31:24,122 DEBUG [f.p.e.c.f.t.TikaInstance] But Tesseract is not installed so we won't run OCR.
19:31:24,568 WARN  [o.a.t.p.PDFParser] J2KImageReader not loaded. JPEG2000 files will not be processed.
See https://pdfbox.apache.org/2.0/dependencies.html#jai-image-io
for optional dependencies.

19:31:24,745 DEBUG [f.p.e.c.f.t.TikaInstance] OCR is activated so we need to configure Tesseract in case we have specific settings.
19:31:24,746 DEBUG [f.p.e.c.f.t.TikaInstance] Tesseract Path set to [/usr/bin/renamed_tesseract].
19:31:24,746 DEBUG [f.p.e.c.f.t.TikaInstance] Tesseract Language set to [deu].
```
However, again tesseract is not called.
