### ISSUE TITLE
fscrawler custom field

### ISSUE THREAD

**Issue by pys6478** [dadoonet/fscrawler#817]
![image](https://user-images.githubusercontent.com/11864076/65497763-b6fe8c80-def5-11e9-98cf-4a6b2e49850e.png)

The path.root field is shown by the folder id.

I want to be seen as folder name, not folder id.
Also, If it is `remove_deleted: false`, can't you confirm that the file has been deleted?

I fixed `\bin\test\_default\7\_settings.json` but it doesn't work.

What should I do?

My ElasticSearch Version
```json
{
  "name" : "568ff2de26ef",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "W-WTEbfBSmGJETTzaeEdVw",
  "version" : {
    "number" : "7.1.1",
    "build_flavor" : "oss",
    "build_type" : "tar",
    "build_hash" : "7a013de",
    "build_date" : "2019-05-23T14:04:00.380842Z",
    "build_snapshot" : false,
    "lucene_version" : "8.0.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```

`_settings.yml`
```yml
---
name: "job_name"
fs:
  url: "C:\\tmp\\es"
  update_rate: "15s"
  excludes:
  - "*/~*"
  json_support: false
  filename_as_id: false
  add_filesize: true
  remove_deleted: true
  add_as_inner_object: false
  store_source: false
  index_content: true
  attributes_support: true
  raw_metadata: true
  xml_support: false
  index_folders: true
  lang_detect: false
  continue_on_error: false
  ocr:
    language: "eng"
    enabled: true
    pdf_strategy: "ocr_and_text"
  follow_symlinks: false
elasticsearch:
  nodes:
  - url: "http://192.168.99.201:9200"
  username: "admin"
  password: "admin"
  bulk_size: 100
  flush_interval: "5s"
  byte_size: "10mb"

```
