### ISSUE TITLE
.mbox not being indexed

### ISSUE THREAD

**Issue by maacl** [dadoonet/fscrawler#910]
**Describe the bug**

Single .mbox file placed in folder not being indexed. emails is available in kibana for index creation but no content is being indexed.

**To Reproduce**

Place .mbox file in /home/mac/Downloads/emails. 

Place the following _settings.yaml file in /home/user/.fscrawler/emails

```
---
name: "emails"
fs:
  url: "/home/mac/Downloads/emails"
  update_rate: "2m"
  includes:
  - "*.mbox"
  excludes:
  - "*/~*"
  json_support: false
  filename_as_id: false
  add_filesize: true
  remove_deleted: true
  add_as_inner_object: false
  store_source: false
  index_content: true
  attributes_support: false
  raw_metadata: false
  xml_support: false
  index_folders: true
  lang_detect: false
  continue_on_error: false
  ocr:
    language: "eng"
    enabled: true
    pdf_strategy: "ocr_and_text"
  follow_symlinks: false
elasticsearch:
  nodes:
  - url: "http://127.0.0.1:9200"
  bulk_size: 100
  flush_interval: "5s"
  byte_size: "10mb"
```
Start fscrawler using:
`bin/fscrawler emails --restart`

emails is available in kibana for index creation but no content is being indexed.

**Expected behavior**

.mbox folder to be indexed.

**Versions:**
 - Ubuntu 19.10
 - fscrawler fscrawler-es7-2.7-SNAPSHOT 
 - elastisearch 7.5.1
 - kibana 7.5.1
