### ISSUE TITLE
XML Parse error on txt files

### ISSUE THREAD

**Issue by aram535** [dadoonet/fscrawler#979]
**Describe the bug**

While scanning text files, app is chucking the file as an invalid XML file that is badly formatted.  I figured it must be tika mis-interpreting the file, I tried to turn off tika with "skip_tika" configuration according to #846 but that did not work.  (Restarted scan with --restart).  The file is not fully searchable in Kibana and is not included in the result set.  (Tested with a small file sample).

**Job Settings**

```yml
name: "idx"
fs:
  url: "/fs/archive/files/"
  update_rate: "60m"
  includes:
    - "*/*.txt"
  json_support: false
  filename_as_id: false
  add_filesize: true
  remove_deleted: true
  add_as_inner_object: false
  store_source: false
  index_content: true
  attributes_support: false
  raw_metadata: false
  xml_support: false
  index_folders: true
  lang_detect: true
  continue_on_error: false
  ocr:
    language: "eng"
    enabled: true
    pdf_strategy: "ocr_and_text"
  follow_symlinks: false
  skip_tika: true
elasticsearch:
  nodes:
    - url: "http://192.168.1.5:9200"
  bulk_size: 100
  flush_interval: "5s"
  byte_size: "10mb"
```

**Logs**

```
06:05:25,072 WARN  [f.p.e.c.f.t.TikaDocParser] Failed to extract [100000] characters of text for [/fs/archive/files/13613.txt]  -> XML parse error -> The markup in the document following the root element must be well-formed.
```

**Expected behavior**

The full content of file should be indexed and searchable.

**Versions:**
 - OS: Linux (CentOS 8)
 - Version: fscrawler-es7-2.7-SNAPSHOT ... ES: 7.8.0

**Comment by dadoonet** [comment]
Could you try to change this setting to -1 ? https://fscrawler.readthedocs.io/en/latest/admin/fs/local-fs.html#extracted-characters

**Comment by aram535** [comment]
Set it to -1:
"Failed to extract [-1] characters of text for .... "

I also tried setting the value to 100%: 
"Failed to extract [25376] characters of text for ... "

Oddly enough it's only some files .... they're all the same permissions, same owner/group (same user as the one running the app), no ACLs.  Even SELinux is disabled on this system.

**Comment by dadoonet** [comment]
Could you run with the `--debug` option?

**Comment by aram535** [comment]
It is Tika that's doing it .... 
`org.apache.tika.exception.TikaException: XML parse error
        at org.apache.tika.parser.xml.XMLParser.parse(XMLParser.java:81) ~[tika-parsers-1.24.1.jar:1.24.1]
        at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280) ~[tika-core-1.24.1.jar:1.24.1]
        at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280) ~[tika-core-1.24.1.jar:1.24.1]
        at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:143) ~[tika-core-1.24.1.jar:1.24.1]`

**Comment by aram535** [comment]
Okay 100% it is Tika that's doing it .. 

`public class TikaTest {
    public static void main(String[] args) throws Exception {
        Path path = Paths.get("/usr/share/nginx/html/x/www.asstr.org/files/Collections/Nepi_Stories/GIRLS/Little Baby Jane.txt");
        File f = path.toFile();

        TikaConfig tika = new TikaConfig();
        Metadata metadata = new Metadata();
        metadata.set(Metadata.RESOURCE_NAME_KEY, f.toString());
        System.out.println("File " + f + " is " + tika.getDetector().detect(TikaInputStream.get(f), metadata));
    }
}`

# ... 1.txt is the plain email with header 
# ...  2.txt is just the body of the email (removed the top 12 lines)

$ java -cp .:./TikaTest.class:./lib/tika-core-1.24.1.jar TikaTest ./1.txt 
File ./1.txt is application/xml
$ java -cp .:./TikaTest.class:./lib/tika-core-1.24.1.jar TikaTest ./2.txt 
File ./2.txt is text/plain

We can turn this into a bug that "skip_tika" is being ignored in the configuration.  I'll work out where the problem with Tika is with them.

**Comment by aram535** [comment]
Okay, 100% it is Tika that's doing it ...

```
public class TikaTest {
    public static void main(String[] args) throws Exception {
        Path path = Paths.get(args[0]);
        File f = path.toFile();

        TikaConfig tika = new TikaConfig();
        Metadata metadata = new Metadata();
        metadata.set(Metadata.RESOURCE_NAME_KEY, f.toString());
        System.out.println("File " + f + " is " + tika.getDetector().detect(TikaInputStream.get(f), metadata));
    }
}
```

... 1.txt is the plain email with header 
...  2.txt is just the body of the email (removed the top 12 lines)

$ java -cp .:./TikaTest.class:./lib/tika-core-1.24.1.jar TikaTest ./1.txt 
File ./1.txt is application/xml
$ java -cp .:./TikaTest.class:./lib/tika-core-1.24.1.jar TikaTest ./2.txt 
File ./2.txt is text/plain

We can turn this into a bug that "skip_tika" is being ignored in the configuration.  I'll work out where the problem with Tika is with them.

**Comment by dadoonet** [comment]
I think that [index_content](https://fscrawler.readthedocs.io/en/latest/admin/fs/local-fs.html#ignore-content) option does this now.

```yaml
name: "test"
fs:
  index_content: false
```
